name: Manual API Call

on:
  repository_dispatch:
    types: [incident_report]

jobs:
  handle-incident:
    runs-on: ubuntu-latest
    steps:
      - name: Print incident report
        run: echo "Incident report received! ${{toJson(github.event.client_payload)}}"
