name: Secrets and Environment

on:
  workflow_dispatch:

jobs:
  secrets_env_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set a secret
        run: echo "SECRET_VALUE=supersecret" >> $GITHUB_ENV

      - name: Use the secret
        run: echo "The secret value is $SECRET_VALUE"

      - name: Use masked secret
        run: |
          echo "The masked secret value is ::add-mask::$SECRET_VALUE"
          echo "Using masked secret value is $SECRET_VALUE"
